### ISSUE TITLE
Using client certificate based auth in Service Fabric

### ISSUE THREAD

**Issue by OscarCR88** [xavierjohn/ClientCertificateMiddleware#8]
HI there
I was trying to make this middleware work with an API inside Service Fabric, but i can't manage to get the  `Context.Connection.ClientCertificate` to have a value other than null. Any help?

**Comment by xavierjohn** [comment]
I don't think this has anything to do with Service Fabric. Sounds like one of two possible things:

The connection isn't HTTPS, which is required.
The client isn't sending a certificate.
